<a href="https://colab.research.google.com/github/AlexanderPiavis/GSB544/blob/main/Practice_Activity_Penguin_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Palmer Penguins Modeling

Import the Palmer Penguins dataset and print out the first few rows.

Suppose we want to predict `species` using the other variables in the dataset.

**Dummify** all variables that require this.

In [6]:
# Code Here
import pandas as pd
import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.compose import make_column_selector, ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder, PolynomialFeatures
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import r2_score
from sklearn.pipeline import Pipeline
from sklearn.neighbors import KNeighborsRegressor, KNeighborsClassifier
from sklearn.tree import DecisionTreeRegressor, DecisionTreeClassifier

!pip install palmerpenguins
from palmerpenguins import load_penguins
penguins = load_penguins().dropna()
penguins['gentoo'] = penguins["species"] == "Gentoo"

X = penguins.drop(["species", "gentoo"], axis = 1)
y = penguins["gentoo"]
# Code Here
ct = ColumnTransformer(
  [
    ("dummify",
    OneHotEncoder(sparse_output = False, handle_unknown='ignore'), # handle_unknown for new dummy vars
    make_column_selector(dtype_include=object)), # Find all columns of a certain type
    ("standardize",
    StandardScaler(),
    make_column_selector(dtype_include=np.number)) # includes any number variable
  ],
  remainder = "drop"
)

Let's use the other variables to predict `species`. Prepare your data and fit the following models on the entire dataset:

* Two kNN models (for different values of K)
* Two decision tree models (for different complexities of trees)

Compute the following, for each of your models, on test data. Keep in mind that you may need to stratify your creation of the training and test data.

* Confusion matrix
* Overall Accuracy
* Precision, Recall, AUC, and F1-score for each species

Create one ROC plot for the species of your choice.

In [7]:
# Code Here
kNN_pipeline5 = Pipeline(
    [("preprocessing", ct),
     ("kNN_regression", KNeighborsClassifier(n_neighbors=5))]
)
kNN_pipeline10 = Pipeline(
    [("preprocessing", ct),
     ("kNN_regression", KNeighborsClassifier(n_neighbors=10))]
)
scores5pre = cross_val_score(kNN_pipeline5, X, y, cv=5, scoring='precision')
scores10pre = cross_val_score(kNN_pipeline10, X, y, cv=5, scoring='precision')
scores5rec = cross_val_score(kNN_pipeline5, X, y, cv=5, scoring='recall')
scores10rec = cross_val_score(kNN_pipeline10, X, y, cv=5, scoring='recall')
scores5f1 = cross_val_score(kNN_pipeline5, X, y, cv=5, scoring='f1')
scores10f1 = cross_val_score(kNN_pipeline10, X, y, cv=5, scoring='f1')
scores5auc = cross_val_score(kNN_pipeline5, X, y, cv=5, scoring='roc_auc_ovr')
scores10auc = cross_val_score(kNN_pipeline10, X, y, cv=5, scoring='roc_auc_ovr')
scores5pre,scores10pre,scores5rec,scores10rec,scores5f1,scores10f1,scores5auc, scores10auc

(array([1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1.]))

In [9]:
tree_pipeline2 = Pipeline(
    [("preprocessing", ct),
     ("tree_regression", DecisionTreeRegressor(max_depth=2))]
)
tree_pipeline3 = Pipeline(
    [("preprocessing", ct),
     ("tree_regression", DecisionTreeRegressor(max_depth=3))]
)
scores2pre = cross_val_score(tree_pipeline2, X, y, cv=5, scoring='precision')
scores3pre = cross_val_score(tree_pipeline3, X, y, cv=5, scoring='precision')
scores2rec = cross_val_score(tree_pipeline2, X, y, cv=5, scoring='recall')
scores3rec = cross_val_score(tree_pipeline3, X, y, cv=5, scoring='recall')
scores2f1 = cross_val_score(tree_pipeline2, X, y, cv=5, scoring='f1')
scores3f1 = cross_val_score(tree_pipeline3, X, y, cv=5, scoring='f1')
scores2auc = cross_val_score(tree_pipeline2, X, y, cv=5, scoring='roc_auc_ovr')
scores3auc = cross_val_score(tree_pipeline3, X, y, cv=5, scoring='roc_auc_ovr')
scores2pre,scores3pre,scores2rec,scores3rec,scores2f1,scores3f1,scores2auc, scores3auc

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.p

(array([0., 0., 1., 1., 0.]),
 array([0., 0., 1., 1., 0.]),
 array([0.      , 0.      , 1.      , 0.984375, 0.      ]),
 array([0.      , 0.      , 1.      , 0.984375, 0.      ]),
 array([0.        , 0.        , 1.        , 0.99212598, 0.        ]),
 array([0.        , 0.        , 1.        , 0.99212598, 0.        ]),
 array([nan, nan, nan, nan, nan]),
 array([nan, nan, nan, nan, nan]))